<?php
/**
 * @package    Packlink_PacklinkPro
 * @author     Packlink Shipping S.L.
 * @copyright  2019 Packlink
 */
?>

<div class="pl-input-mask hidden" id="pl-map-modal">
    <div class="pl-map-modal" id="pl-modal-content">
        <div class="pl-modal-spinner-wrapper disabled" id="pl-modal-spinner">
            <div class="pl-modal-spinner"></div>
        </div>
        <div class="pl-close-modal" id="pl-close-modal-btn">x</div>

        <location-picker>
            <div class="lp-content" data-lp-id="content">
                <div class="lp-locations">
                    <div class="lp-input-wrapper">
                        <div class="input">
                            <input type="text" data-lp-id="search-box">
                            <span class="label" data-lp-id="search-box-label"></span>
                        </div>
                    </div>

                    <div data-lp-id="locations"></div>
                </div>
            </div>
        </location-picker>

    </div>
</div>

<location-picker-template hidden>
    <div class="lp-template" id="template-container">
        <div data-lp-id="working-hours-template" class="lp-hour-wrapper">
            <div class="day" data-lp-id="day">
            </div>
            <div class="hours" data-lp-id="hours">
            </div>
        </div>

        <div class="lp-location-wrapper" data-lp-id="location-template">
            <div class="radio-button lp-collapse">
                <div class="lp-radio"></div>
            </div>
            <div class="composite lp-expand">
                <div class="street-name uppercase" data-lp-id="composite-address"></div>
                <div class="lp-working-hours-btn excluded" data-lp-composite
                     data-lp-id="show-composite-working-hours-btn"></div>
                <div data-lp-id="composite-working-hours" class="lp-working-hours">

                </div>
                <div class="lp-select-column">
                    <div class="lp-select-button excluded" data-lp-id="composite-select-btn"></div>
                    <a class="excluded" href="#" data-lp-id="composite-show-on-map" target="_blank"></a>
                </div>
            </div>
            <div class="name uppercase lp-collapse" data-lp-id="location-name"></div>
            <div class="street lp-collapse">
                <div class="street-name uppercase" data-lp-id="location-street"></div>
                <div class="lp-working-hours-btn excluded" data-lp-id="show-working-hours-btn"></div>
                <div data-lp-id="working-hours" class="lp-working-hours">

                </div>
            </div>
            <div class="city uppercase lp-collapse" data-lp-id="location-city">
            </div>
            <div class="lp-select-column lp-collapse">
                <div class="lp-select-button excluded" data-lp-id="select-btn"></div>
            </div>
            <a class="excluded lp-collapse" href="#" data-lp-id="show-on-map" target="_blank">
                <div class="lp-show-on-map-btn excluded"></div>
            </a>
        </div>
    </div>
</location-picker-template>

<button type="button" id="pl-drop-off-button" style="display: none">
    <span data-bind="i18n: 'Select drop-off location'"></span>
</button>

<div id="pl-drop-off-details" style="display: none">
    <span data-bind="i18n: 'Package will be delivered to:'"></span>
    <span id="pl-drop-off-address"></span>
</div>

<span hidden id="pl-select-drop-off-text" data-bind="i18n: 'Select drop-off location'"></span>
<span hidden id="pl-change-drop-off-text" data-bind="i18n: 'Change drop-off location'"></span>


<script>
    (function () {
        require(
            [
                'Magento_Checkout/js/model/quote'
            ],
            function (quote) {
                let logos = [];
                logos['backup'] = '<?= $block->getDefaultCarrierLogoUrl() ?>';

                <?php foreach ($block->getMethodsWithEnabledLogos() as $id => $logoUrl) : ?>
                logos['<?= $id ?>'] = '<?= $logoUrl ?>';
                <?php endforeach; ?>

                // wait until shipping methods containers are rendered
                let timer = setInterval(assignControllers, 200);

                function assignControllers() {
                    let block = document.querySelector('.table-checkout-shipping-method');
                    if (block) {
                        clearInterval(timer);

                        let controller = new Packlink.CheckoutShippingMethods();
                        controller.init(
                            block,
                            quote,
                            <?= current($block->getQuoteItemWeights()) ?>,
                            '<?= $block->getUrl('packlink/frontend/location') ?>',
                            '.actions-toolbar button.continue,.actions-toolbar button.checkout',
                            false,
                            logos,
                            '<?= $block->getCurrentLanguageCode() ?>'
                        );
                    }
                }
            },
            function (error) {
                console.log(error);
            }
        );
    })();
</script>
