<?php
/**
 * @package    Packlink_PacklinkPro
 * @author     Packlink Shipping S.L.
 * @copyright  2022 Packlink
 */

/** @var Packlink\PacklinkPro\Block\Adminhtml\Content\Dashboard $block */
?>

<div id="pl-page">
    <header id="pl-main-header">
        <div class="pl-main-logo">
            <img src="https://cdn.packlink.com/apps/giger/logos/packlink-pro.svg" alt="logo">
        </div>
        <div class="pl-header-holder" id="pl-header-section"></div>
    </header>

    <main id="pl-main-page-holder"></main>

    <div class="pl-spinner pl-hidden" id="pl-spinner">
        <div></div>
    </div>

    <template id="pl-alert">
        <div class="pl-alert-wrapper">
            <div class="pl-alert">
                <span class="pl-alert-text"></span>
                <i class="material-icons">close</i>
            </div>
        </div>
    </template>

    <template id="pl-modal">
        <div id="pl-modal-mask" class="pl-modal-mask pl-hidden">
            <div class="pl-modal">
                <div class="pl-modal-close-button">
                    <i class="material-icons">close</i>
                </div>
                <div class="pl-modal-title">

                </div>
                <div class="pl-modal-body">

                </div>
                <div class="pl-modal-footer">
                </div>
            </div>
        </div>
    </template>

    <template id="pl-error-template">
        <div class="pl-error-message" data-pl-element="error">
        </div>
    </template>
</div>

<script src="<?= $block->escapeUrl(($block->getViewFileUrl('Packlink_PacklinkPro::packlink/js/GridResizerService.js'))); ?>"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
      rel="stylesheet"/>
<script>
    document.addEventListener('DOMContentLoaded', function () {
            let ajaxService = Packlink.ajaxService,
                stateControllerUrl = "<?= $block->escapeUrl($block->getControllerUrl('ModuleState', 'getCurrentState')); ?>",
                baseResourcesUrl = "<?= $block->escapeUrl($block->getViewFileUrl('Packlink_PacklinkPro::packlink')); ?>",
                // URLs for AJAX actions have to be loaded here
                // if URLs are loaded from backend all form keys will not be generated correctly
                // and all AJAX requests will fail
                configuration = {
                    'login': {
                        'submit': "<?= $block->escapeUrl($block->getControllerUrl('Login', 'login')); ?>",
                        'listOfCountriesUrl': "<?= $block->escapeUrl($block->getControllerUrl('RegistrationRegions', 'getRegions')); ?>",
                        'logoPath': '',
                    },
                    'register': {
                        'getRegistrationData': "<?= $block->escapeUrl($block->getControllerUrl('Registration', 'getRegisterData')); ?>",
                        'submit': "<?= $block->escapeUrl($block->getControllerUrl('Registration', 'register'))?>",
                    },
                    'onboarding-state': {
                        'getState': "<?= $block->escapeUrl($block->getControllerUrl('Onboarding', 'getCurrentState')); ?>",
                    },
                    'onboarding-welcome': {},
                    'onboarding-overview': {
                        'defaultParcelGet': "<?= $block->escapeUrl($block->getControllerUrl('DefaultParcel', 'getDefaultParcel')); ?>",
                        'defaultWarehouseGet': "<?= $block->escapeUrl($block->getControllerUrl('DefaultWarehouse', 'getDefaultWarehouse')); ?>",
                    },
                    'default-parcel': {
                        'getUrl': "<?= $block->escapeUrl($block->getControllerUrl('DefaultParcel', 'getDefaultParcel')); ?>",
                        'submitUrl': "<?= $block->escapeUrl($block->getControllerUrl('DefaultParcel', 'setDefaultParcel')); ?>",
                    },
                    'default-warehouse': {
                        'getUrl': "<?= $block->escapeUrl($block->getControllerUrl('DefaultWarehouse', 'getDefaultWarehouse')); ?>",
                        'getSupportedCountriesUrl': "<?= $block->escapeUrl($block->getControllerUrl('DefaultWarehouse', 'getSupportedCountries')); ?>",
                        'submitUrl': "<?= $block->escapeUrl($block->getControllerUrl('DefaultWarehouse', 'setDefaultWarehouse')); ?>",
                        'searchPostalCodesUrl': "<?= $block->escapeUrl($block->getControllerUrl('DefaultWarehouse', 'searchPostalCodes')); ?>",
                    },
                    'cash-on-delivery': {
                        'getDataUrl': "<?= $block->escapeUrl($block->getControllerUrl('CashOnDelivery', 'getCashOnDeliveryConfig')); ?>",
                        'submitDataUrl': "<?= $block->escapeUrl($block->getControllerUrl('CashOnDelivery', 'saveCashOnDeliveryConfig')); ?>",
                    },
                    'configuration': {
                        'getDataUrl': "<?= $block->escapeUrl( $block->getControllerUrl('Configuration', 'getData')); ?>",
                    },
                    'system-info': {
                        'getStatusUrl': "<?= $block->escapeUrl($block->getControllerUrl('Debug', 'getStatus')); ?>",
                        'setStatusUrl': "<?= $block->escapeUrl($block->getControllerUrl('Debug', 'setStatus')); ?>",
                    },
                    'order-status-mapping': {
                        'getMappingAndStatusesUrl': "<?= $block->escapeUrl($block->getControllerUrl('OrderStateMapping', 'getMappingsAndStatuses')); ?>",
                        'setUrl': "<?=$block->escapeUrl($block->getControllerUrl('OrderStateMapping', 'setMappings')); ?>",
                    },
                    'my-shipping-services': {
                        'getServicesUrl': "<?= $block->escapeUrl($block->getControllerUrl('ShippingMethods', 'getActive')); ?>",
                        'deleteServiceUrl': "<?= $block->escapeUrl($block->getControllerUrl('ShippingMethods', 'deactivate')); ?>",
                        'getCurrencyDetailsUrl': "<?= $block->escapeUrl($block->getControllerUrl('SystemInfo', 'get')); ?>",
                        'systemId': "<?= $block->escapeUrl($block->getCurrentStoreId()); ?>",
                    },
                    'pick-shipping-service': {
                        'getActiveServicesUrl': "<?= $block->escapeUrl($block->getControllerUrl('ShippingMethods', 'getActive')); ?>",
                        'getServicesUrl': "<?= $block->escapeUrl($block->getControllerUrl('ShippingMethods', 'getInactive')); ?>",
                        'getTaskStatusUrl': "<?= $block->escapeUrl($block->getControllerUrl('ShippingMethods', 'getTaskStatus')); ?>",
                        'startAutoConfigureUrl': "<?= $block->escapeUrl($block->getControllerUrl('AutoConfigure', 'start')); ?>",
                        'disableCarriersUrl':
                            '',
                        'getCurrencyDetailsUrl': "<?= $block->escapeUrl($block->getControllerUrl('SystemInfo', 'get')); ?>",
                        'systemId': "<?= $block->escapeUrl($block->getCurrentStoreId()); ?>",
                        'enqueue': "<?= $block->escapeUrl($block->getControllerUrl('ManualRefresh', 'refresh')); ?>",
                        'getTaskStatus': "<?= $block->escapeUrl($block->getControllerUrl('ManualRefresh', 'getTaskStatus')); ?>"
                    },
                    'edit-service': {
                        'getServiceUrl': "<?= $block->escapeUrl($block->getControllerUrl('ShippingMethods', 'getShippingMethod')); ?>",
                        'saveServiceUrl': "<?= $block->escapeUrl($block->getControllerUrl('ShippingMethods', 'save')); ?>",
                        'getTaxClassesUrl': '',
                        'getCountriesListUrl': "<?=$block->escapeUrl($block->getControllerUrl('ShippingCountries', 'getAll')); ?>",
                        'getCurrencyDetailsUrl': "<?= $block->escapeUrl($block->getControllerUrl('SystemInfo', 'get')); ?>",
                        'hasTaxConfiguration': false,
                        'hasCountryConfiguration': true,
                        'canDisplayCarrierLogos': true,
                    }
                };

            ajaxService.get(
                "<?= $block->escapeUrl($block->getUrlHelper()->getBackendUrl(
                    'packlink/content/dashboard',
                    ['action' => 'getTranslations']
                )); ?>",
                function (response) {
                    Packlink.translations = {
                        default: response['default'],
                        current: response['current']
                    };
                }
            );


            ajaxService.get(
                "<?= $block->escapeUrl($block->getUrlHelper()->getBackendUrl(
                    'packlink/content/dashboard',
                    ['action' => 'getTemplates']
                )); ?>",
                function (response) {
                    Packlink.state = new Packlink.StateController(
                        {
                            baseResourcesUrl: baseResourcesUrl,
                            stateUrl: stateControllerUrl,
                            pageConfiguration: configuration,
                            templates: response
                        }
                    );

                    Packlink.state.display();

                    calculateContentHeight();
                }
            );

            /**
             * Calculates content height.
             */
            function calculateContentHeight() {
                let content = document.getElementById('pl-main-page-holder');
                let localOffset = content.offsetTop + 20 + 35; // negative margin and footer bar

                let body = document.getElementsByTagName('body')[0];
                content.style.height = body.clientHeight - localOffset + 'px';

                setTimeout(calculateContentHeight, 250);
            }
        },
        false
    );
</script>
