<?php
/**
 * @package    Packlink_PacklinkPro
 * @author     Packlink Shipping S.L.
 * @copyright  2019 Packlink
 */

/** @var Packlink\PacklinkPro\Block\Adminhtml\Content\Login $block */
?>

<div class="pl-login-page" id="pl-main-page-holder">
    <div class="pl-login-page-side-img-wrapper pl-collapse">
        <img
                src="<?php echo $block->getViewFileUrl('Packlink_PacklinkPro::images/logo-pl.svg'); ?>"
                class="pl-login-icon"
                alt="<?php echo $block->escapeQuote(__('Packlink PRO Shipping')); ?>"
        >
    </div>
    <div class="pl-login-page-content-wrapper">
        <div class="pl-register-form-wrapper">
            <div class="pl-register-btn-section-wrapper">
                <?php echo $block->escapeQuote(__("Don't have an account?")); ?>
                <button type="button" id="pl-register-btn" class="button button-primary button-register">
                    <?php echo $block->escapeQuote(__('Register')); ?>
                </button>
            </div>
            <div class="pl-register-country-section-wrapper" id="pl-register-form">
                <div class="pl-register-form-close-btn">
                    <svg id="pl-register-form-close-btn" width="24" height="24" viewBox="0 0 22 22"
                         xmlns="http://www.w3.org/2000/svg">
                        <g fill="none" fill-rule="evenodd">
                            <path
                                d="M11 21c5.523 0 10-4.477 10-10S16.523 1 11 1 1 5.477 1 11s4.477 10 10 10zm0 1C4.925 22 0 17.075 0 11S4.925 0 11 0s11 4.925 11 11-4.925 11-11 11z"
                                fill="#2095F2" fill-rule="nonzero"/>
                            <path d="M7.5 7.5l8 7M15.5 7.5l-8 7" stroke="#2095F2" stroke-linecap="square"/>
                        </g>
                    </svg>
                </div>
                <div class="pl-register-country-title-wrapper">
                    <?php echo $block->escapeQuote(__('Select country to start')); ?>
                </div>
                <input
                    type="hidden"
                    id="pl-countries-url"
                    value="<?php echo $block->getControllerUrl('Registration', 'getSupportedCountries'); ?>"
                />
                <input type="hidden" id="pl-logo-path" value="<?php echo $block->getViewFileUrl(
                    'Packlink_PacklinkPro::images/flags/'
                ); ?>"/>
                <div class="pl-register-country-list-wrapper">
                </div>
            </div>
        </div>
        <div>
            <div class="pl-login-form-header">
                <div class="pl-login-form-title-wrapper">
                    <?php echo $block->escapeQuote(__('Allow Magento to connect to PacklinkPRO')); ?>
                </div>
                <div class="pl-login-form-text-wrapper">
                    <?php echo $block->escapeQuote(__('Your API key can be found under')); ?>
                    pro.packlink/<strong>Settings/PacklinkPROAPIkey</strong>
                </div>
            </div>
            <div class="pl-login-form-label-wrapper">
                <?php echo $block->escapeQuote(__('Connect your account')); ?>
            </div>
            <form method="POST" action="<?php echo $this->getUrl('packlink/content/login'); ?>">
                <?php echo $this->getBlockHtml('formkey') ?>
                <div class="pl-login-form-wrapper">
                    <fieldset class="form-group pl-form-section-input pl-text-input">
                        <input type="text" class="form-control" id="pl-login-api-key" name="api_key" required/>
                        <span class="pl-text-input-label" id="pl-login-api-key-label">
                            <?php echo $block->escapeQuote(__('Api key')); ?>
                        </span>
                    </fieldset>
                </div>
                <div>
                    <button type="submit" name="login" class="button button-primary button-login">
                        <?php echo $block->escapeQuote(__('Log in')); ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var Packlink = window.Packlink || {};

    /**
     * Initializes register form on login page.
     */
    function initRegisterForm() {
        let populateCountryList = function (response) {
                let countryList = document.getElementsByClassName('pl-register-country-list-wrapper')[0],
                    logoPath = document.getElementById('pl-logo-path').value;

                if (countryList.childElementCount > 0) {
                    return;
                }

                for (let code in response) {
                    let supportedCountry = response[code],
                        linkElement = document.createElement('a'),
                        countryElement = document.createElement('div'),
                        imageElement = document.createElement('img'),
                        nameElement = document.createElement('div');

                    linkElement.href = supportedCountry.registration_link;
                    linkElement.target = '_blank';

                    countryElement.classList.add('pl-country');

                    imageElement.src = logoPath + '/' + supportedCountry.code + '.svg';
                    imageElement.classList.add('pl-country-logo');
                    imageElement.alt = supportedCountry.name;

                    countryElement.appendChild(imageElement);

                    nameElement.classList.add('pl-country-name');
                    nameElement.innerText = supportedCountry.name;

                    countryElement.appendChild(nameElement);
                    linkElement.appendChild(countryElement);
                    countryList.appendChild(linkElement);
                }
            },
            registerBtnClicked = function () {
                let form = document.getElementById('pl-register-form');
                let ajaxService = Packlink.ajaxService;
                form.style.display = 'block';

                let closeBtn = document.getElementById('pl-register-form-close-btn');
                closeBtn.addEventListener('click', function () {
                    form.style.display = 'none';
                });

                let supportedCountriesUrl = document.getElementById('pl-countries-url').value;

                ajaxService.get(supportedCountriesUrl, populateCountryList);
            };

        let btn = document.getElementById('pl-register-btn');
        btn.addEventListener('click', registerBtnClicked, true);
    }

    document.addEventListener('DOMContentLoaded', function () {
        Packlink.utilityService.configureInputElements();
    });

    initRegisterForm();
    calculateContentHeight();

    /**
     * Calculates content height.
     */
    function calculateContentHeight() {
        let content = document.getElementById('pl-main-page-holder');
        let localOffset = content.offsetTop + 20 + 35; // negative margin and footer bar

        let body = document.getElementsByTagName('body')[0];
        content.style.height = body.clientHeight - localOffset + 'px';

        setTimeout(calculateContentHeight, 250);
    }
</script>